[package]
name = "langchain_rs"
version = "0.0.1"                                       # remember to update html_root_url
authors = ["Ryo Kanazawa <ryo.kanazawa34@gmail.com>"]
build = "build.rs"
categories = ["encoding", "no-std", "no-std::no-alloc"]
description = "Rust version of Langchain"
documentation = "https://docs.rs/langchain_rs"
edition = "2018"
homepage = "https://github.com/gyroflaw/langchain_rs"
keywords = ["serde", "serialization", "no_std"]
license = "Apache-2.0"
readme = "crates-io.md"
repository = "https://github.com/serde-rs/serde"
rust-version = "1.31"


### FEATURES #################################################################

[features]
default = ["std"]
